services:
  frontend:
    build:
      context: ./frontend
    command: preview
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    command: prod
    depends_on:
      - mongodb
    volumes:
      - media_container:/backend/media
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
  nginx:
    build:
      context: ./nginx
    ports:
      - 8000:80
    depends_on:
      - frontend
      - backend

volumes:
  mongodb_data_container:
  media_container:
